- project:
    templates:
      - openstack-python3-charm-jobs-ussuri
      - openstack-cover-charm-jobs
    check:
      jobs:
        - charmbuild
    vars:
      charm_build_name: gnocchi
      charmbuild_charmcraft_channel: 2.x/stable
